# Generated by Django 4.1.7 on 2023-04-05 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Device name')),
                ('uuid', models.CharField(max_length=128, verbose_name='Device uuid')),
                ('revoke', models.IntegerField(default=0, verbose_name='Revoke')),
                ('block', models.IntegerField(default=0, verbose_name='Block')),
                ('primary', models.IntegerField(default=0, verbose_name='Primary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '11. Session',
            },
        ),
    ]
