# Generated by Django 4.1.7 on 2023-04-05 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expiredtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('in_merchant', models.CharField(max_length=64, null=True)),
                ('in_terminal', models.CharField(max_length=64, null=True)),
                ('in_terminal_account', models.CharField(max_length=128, null=True)),
                ('out_merchant', models.CharField(max_length=64, null=True)),
                ('out_terminal', models.CharField(max_length=64, null=True)),
                ('out_terminal_account', models.CharField(max_length=128, null=True)),
                ('percentage', models.FloatField(default=0.0, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('desc_uz', models.TextField()),
                ('desc_en', models.TextField()),
                ('desc_ru', models.TextField()),
                ('body_uz', models.TextField()),
                ('body_en', models.TextField()),
                ('body_ru', models.TextField()),
                ('image_uz', models.CharField(max_length=255)),
                ('image_en', models.CharField(max_length=255)),
                ('image_ru', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
                ('viewed', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='TransferSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64, null=True)),
                ('receiver', models.CharField(max_length=64, null=True)),
                ('amount', models.FloatField(null=True)),
                ('currency', models.IntegerField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('pay_type', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_save', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaynetSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(null=True)),
                ('provider_id', models.IntegerField(null=True)),
                ('service_id', models.IntegerField(null=True)),
                ('fields', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paynet_save', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=255, null=True, unique=True)),
                ('t_id', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(null=True)),
                ('pay_type', models.IntegerField(null=True)),
                ('sender_token', models.CharField(max_length=255, null=True)),
                ('sender_number', models.CharField(max_length=100, null=True)),
                ('sender_expire', models.CharField(max_length=10, null=True)),
                ('sender_mask', models.CharField(max_length=100, null=True)),
                ('receiver_token', models.CharField(max_length=255, null=True)),
                ('receiver_number', models.CharField(max_length=100, null=True)),
                ('receiver_mask', models.CharField(max_length=100, null=True)),
                ('receiver_name', models.CharField(max_length=255, null=True)),
                ('receiver', models.CharField(max_length=255, null=True)),
                ('debit_state', models.CharField(max_length=64, null=True)),
                ('debit_description', models.CharField(max_length=255, null=True)),
                ('debit_amount', models.FloatField(null=True)),
                ('debit_currency', models.CharField(max_length=10, null=True)),
                ('credit_state', models.CharField(max_length=64, null=True)),
                ('credit_description', models.CharField(max_length=255, null=True)),
                ('credit_amount', models.FloatField(null=True)),
                ('credit_currency', models.CharField(max_length=10, null=True)),
                ('rate', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('description', jsonfield.fields.JSONField(null=True)),
                ('type_description', jsonfield.fields.JSONField(null=True)),
                ('merchant', models.CharField(max_length=64, null=True)),
                ('terminal', models.CharField(max_length=64, null=True)),
                ('note', models.CharField(max_length=128, null=True)),
                ('is_credit', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '12. Monitoring',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Form',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('balance', models.FloatField(max_length=128)),
                ('number', models.CharField(default=0, max_length=128)),
                ('expire', models.CharField(max_length=10)),
                ('mask', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128, null=True)),
                ('card_owner', models.CharField(max_length=256, null=True)),
                ('card_logo', models.CharField(max_length=128)),
                ('bank_logo', models.CharField(blank=True, max_length=128, null=True)),
                ('is_unired', models.IntegerField()),
                ('is_primary', models.IntegerField()),
                ('is_verified', models.IntegerField(default=0)),
                ('card_registered_phone', models.CharField(max_length=50, null=True)),
                ('is_salary', models.IntegerField()),
                ('type', models.IntegerField()),
                ('blocked', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
