#  Xudikk  2023/3/29.
#
#  Created by Xudoyberdi Egamberdiyev
#
#  Please contact before making any changes
#
#  Tashkent, Uzbekistan

UZCARD_TO_UZCARD = 0
UZCARD_TO_HUMO = 1
HUMO_TO_HUMO = 2
HUMO_TO_UZCARD = 3
UZCARD_TO_VISA_USD = 4
VISA_USD_TO_UZCARD = 5
SUM_TO_VISA_USD = 6
VISA_USD_TO_SUM = 7
VISA_USD_TO_VISA_USD = 8
UZCARD_TO_VISA_SUM = 9
VISA_SUM_TO_UZCARD = 10
HUMO_TO_VISA_SUM = 11
VISA_SUM_TO_HUMO = 12
VISA_SUM_TO_VISA_SUM = 13
UZCARD_TO_TCB = 14
HUMO_TO_TCB = 15
UZCARD_TO_TJ = 16
HUMO_TO_TJ = 17
UZCARD_TO_PAYNET = 18
HUMO_TO_PAYNET = 19
MTS_TO_UZ_TRANSFER = 20
MTS_TO_UZ_PAYNET = 21
TCB_TO_UZ_TRANSFER = 22
TCB_TO_UZ_PAYNET = 23
UZ_TO_TCB = 24
UZ_TO_ARMENIA = 25
UZ_TO_TURKEY = 26
UZ_TO_KAZAKH = 27
UZ_TO_AZR = 28
UZ_TO_MKO = 29